[theme]
primaryColor = "#FF5733"
backgroundColor = "#FFFFFF"   # White background
secondaryBackgroundColor = "#F0F0F0"   # Light gray secondary background
textColor = "#333333"   # Dark gray text color

